dist: bionic

sudo: required

language: perl

perl:
  - "5.26-shrplib"

before_install:
  - ./scripts/travis_before_install.sh

install:
  - ./scripts/travis_install.sh

script:
  - ./scripts/travis_script.sh
